# -*- coding: utf-8 -*-
"""ELECTRA-small.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goAZ3NIF3ODJ5lAFacqP9IPZvMBm9vSp

ELECTRA-small
"""

!pip install -q transformers==4.40.0 torch torchvision --upgrade
!pip install -q scikit-learn pandas matplotlib seaborn textblob vaderSentiment joblib tqdm shap

import nltk
nltk.download('punkt')

import os
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import torch
from transformers import AutoTokenizer, AutoModel
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from textblob import TextBlob
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, f1_score, classification_report,
                             confusion_matrix, precision_score, recall_score)
from sklearn.dummy import DummyClassifier
import seaborn as sns
import matplotlib.pyplot as plt
import joblib
import random

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

MODEL_SAVE_DIR = "saved_model"
os.makedirs(MODEL_SAVE_DIR, exist_ok=True)

# CREATE NEUTRAL EXAMPLES (Split into train and held-out test)

print("\n" + "="*70)
print("[1/8] CREATING NEUTRAL EXAMPLES")
print("="*70)

# TRAINING neutral examples
neutral_train = [
    # General knowledge
    "What's the weather like today?", "How do I cook pasta?",
    "What time is it in Tokyo?", "What's the capital of France?",
    "How tall is Mount Everest?", "When did World War 2 end?",
    "Who wrote Romeo and Juliet?", "What's the speed of light?",
    "How many continents are there?", "What's the largest ocean?",
    "What year was the moon landing?", "Who painted the Mona Lisa?",

    # Math
    "What's 15% of 200?", "Calculate 47 times 23",
    "What's the square root of 144?", "Convert 5 miles to kilometers",
    "What's 2 to the power of 10?", "Solve 3x + 5 = 20",

    # Practical help
    "Help me write an email to my boss", "Can you proofread this paragraph?",
    "Summarize this article for me", "Translate hello to Spanish",
    "What's a good recipe for cookies?", "How do I change a tire?",
    "What's the best way to learn Python?", "Can you explain machine learning?",
    "Help me plan a trip to Paris", "What should I pack for camping?",

    # Coding
    "Write a function to sort a list", "How do I create a for loop in Python?",
    "Explain what an API is", "What's the difference between HTTP and HTTPS?",
    "How do I connect to a database?", "Debug this code for me",
    "What's object-oriented programming?", "How do I use Git?",
    "Explain recursion with an example", "What are design patterns?",

    # Creative but neutral
    "Tell me a joke", "Write a haiku about nature",
    "Give me a fun fact", "What's an interesting history story?",
    "Recommend a good book", "What movie should I watch tonight?",

    # Explanations
    "What is photosynthesis?", "Explain how the stock market works",
    "What causes earthquakes?", "How does WiFi work?",
    "What is blockchain?", "Explain the water cycle",
    "What is inflation?", "How do vaccines work?",

    # Simple conversational
    "Hello, how are you?", "Thanks for your help",
    "Can you repeat that?", "I didn't understand, please clarify",
    "What can you help me with?", "Give me some options",

    # Definitions
    "What's the meaning of serendipity?", "How do you pronounce quinoa?",
    "Give me synonyms for happy", "What's the opposite of difficult?",

    # Neutral requests
    "What's better for health, tea or coffee?",
    "Should I learn Spanish or French?",
    "What's the best time to exercise?",
    "Books or audiobooks, which is better?",
]

# HELD-OUT TEST neutral examples (completely different from training)
neutral_test_holdout = [
    # Different general knowledge
    "What's the population of Canada?", "How deep is the Mariana Trench?",
    "Who invented the telephone?", "What's the smallest country?",
    "When was the Eiffel Tower built?", "What causes rainbows?",

    # Different math
    "What's 33% of 900?", "Calculate 128 divided by 4",
    "What's the cube root of 27?", "Convert 100 Fahrenheit to Celsius",

    # Different practical help
    "How do I remove a coffee stain?", "What's a good gift for a friend?",
    "How do I start meditating?", "What plants are easy to grow indoors?",
    "How do I negotiate a salary?", "What's proper email etiquette?",

    # Different coding
    "How do I center a div in CSS?", "What's the difference between Java and JavaScript?",
    "Explain what a hash table is", "How do I handle exceptions in Python?",

    # Different creative
    "Write a limerick about cats", "Give me a random trivia question",
    "What's a good icebreaker question?", "Suggest a creative date idea",

    # Different explanations
    "How do magnets work?", "What is cryptocurrency mining?",
    "Why is the sky blue?", "How do touch screens work?",

    # Different conversational
    "Good evening!", "Could you rephrase that?",
    "What are my options here?", "Let me think about that",
]

print(f"Training neutral examples: {len(neutral_train)}")
print(f"Held-out test neutral examples: {len(neutral_test_holdout)}")

# LOAD AND PREPARE DATA
print("\n" + "="*70)
print("[2/8] LOADING AND PREPARING DATA")
print("="*70)

# Load original data
df_original = pd.read_csv("darkbench.csv")
df_original = df_original.dropna(subset=['input', 'target']).reset_index(drop=True)
print(f"Original dataset: {len(df_original)} rows")

# Split original data into train and test FIRST (before adding neutrals)
df_orig_train, df_orig_test = train_test_split(
    df_original, test_size=0.20, random_state=RANDOM_SEED, stratify=df_original['target']
)
print(f"Original train: {len(df_orig_train)}, Original test: {len(df_orig_test)}")

# Create neutral dataframes
df_neutral_train = pd.DataFrame({'input': neutral_train, 'target': 'neutral'})
df_neutral_test = pd.DataFrame({'input': neutral_test_holdout, 'target': 'neutral'})

# Combine: train with train neutrals, test with test neutrals
df_train_full = pd.concat([df_orig_train, df_neutral_train], ignore_index=True)
df_test_full = pd.concat([df_orig_test, df_neutral_test], ignore_index=True)

# Shuffle
df_train_full = df_train_full.sample(frac=1, random_state=RANDOM_SEED).reset_index(drop=True)
df_test_full = df_test_full.sample(frac=1, random_state=RANDOM_SEED).reset_index(drop=True)

print(f"\nFinal training set: {len(df_train_full)} rows")
print(f"Final test set: {len(df_test_full)} rows (with DIFFERENT neutral examples)")

print(f"\nTraining class distribution:\n{df_train_full['target'].value_counts()}")
print(f"\nTest class distribution:\n{df_test_full['target'].value_counts()}")

# FEATURE EXTRACTION FUNCTION
print("\n" + "="*70)
print("[3/8] SETTING UP FEATURE EXTRACTION")
print("="*70)

vader = SentimentIntensityAnalyzer()

MODEL_NAME = "google/electra-small-discriminator"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
electra_model = AutoModel.from_pretrained(MODEL_NAME)
electra_model.to(device)
electra_model.eval()

def extract_sentiment_features(texts_list):
    features = []
    for t in tqdm(texts_list, desc="Sentiment"):
        tb = TextBlob(t)
        vd = vader.polarity_scores(t)
        features.append([
            tb.sentiment.polarity, tb.sentiment.subjectivity,
            vd['neg'], vd['neu'], vd['pos'], vd['compound']
        ])
    return np.array(features, dtype=np.float32)

def batch_encode_texts(texts_list, batch_size=32):
    all_embeddings = []
    with torch.no_grad():
        for i in tqdm(range(0, len(texts_list), batch_size), desc="Embeddings"):
            batch = texts_list[i:i+batch_size]
            enc = tokenizer(batch, padding=True, truncation=True,
                           return_tensors="pt", max_length=256)
            input_ids = enc['input_ids'].to(device)
            attention_mask = enc['attention_mask'].to(device)
            out = electra_model(input_ids=input_ids, attention_mask=attention_mask)
            last_hidden = out.last_hidden_state
            mask = attention_mask.unsqueeze(-1).expand(last_hidden.size()).float()
            summed = torch.sum(last_hidden * mask, dim=1)
            counts = torch.clamp(mask.sum(dim=1), min=1e-9)
            mean_pooled = (summed / counts).cpu().numpy()
            all_embeddings.append(mean_pooled)
    return np.vstack(all_embeddings)

def extract_all_features(texts_list):
    """Extract combined sentiment + embedding features."""
    sent_feats = extract_sentiment_features(texts_list)
    emb_feats = batch_encode_texts(texts_list)
    return np.concatenate([emb_feats, sent_feats], axis=1)

# EXTRACT FEATURES FOR TRAIN AND TEST
print("\n" + "="*70)
print("[4/8] EXTRACTING FEATURES")
print("="*70)

print("\nProcessing training data...")
X_train = extract_all_features(df_train_full['input'].tolist())
y_train_labels = df_train_full['target'].tolist()

print("\nProcessing test data...")
X_test = extract_all_features(df_test_full['input'].tolist())
y_test_labels = df_test_full['target'].tolist()

print(f"\nTraining features shape: {X_train.shape}")
print(f"Test features shape: {X_test.shape}")

# Encode labels
le = LabelEncoder()
le.fit(y_train_labels + y_test_labels)  # Fit on all labels
y_train = le.transform(y_train_labels)
y_test = le.transform(y_test_labels)

print(f"Classes ({len(le.classes_)}): {list(le.classes_)}")

# SCALE AND TRAIN
print("\n" + "="*70)
print("[5/8] TRAINING CLASSIFIER")
print("="*70)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

clf = LogisticRegression(
    max_iter=5000, class_weight='balanced', random_state=RANDOM_SEED, solver='saga'
)
clf.fit(X_train_scaled, y_train)
print("Training complete!")

# FEATURE IMPORTANCE ANALYSIS
print("\n" + "="*70)
print("[6/8] FEATURE IMPORTANCE ANALYSIS")
print("="*70)

# Simple feature importance
feature_importance = abs(clf.coef_).mean(axis=0)
top_20_idx = np.argsort(feature_importance)[-20:][::-1]

print("\n📊 TOP 20 MOST IMPORTANT FEATURES:")
print("="*50)

# Create feature names
feature_names = []
for i in range(256):  # ELECTRA embedding dimensions
    feature_names.append(f"electra_{i:03d}")
feature_names.extend(["textblob_polarity", "textblob_subjectivity",
                      "vader_neg", "vader_neu", "vader_pos", "vader_compound"])

print(f"{'Rank':<4} {'Feature':<20} {'Importance':<12} {'Type':<15}")
print("-" * 50)
for i, idx in enumerate(top_20_idx):
    feat_name = feature_names[idx]
    feat_type = "SENTIMENT" if idx >= 256 else "ELECTRA"
    print(f"{i+1:<4} {feat_name:<20} {feature_importance[idx]:.6f}   {feat_type:<15}")

# Plot feature importance
plt.figure(figsize=(12, 6))
top_10_importance = feature_importance[top_20_idx[:10]]
top_10_names = [feature_names[idx] for idx in top_20_idx[:10]]
colors = ['red' if 'vader' in name or 'textblob' in name else 'blue' for name in top_10_names]

plt.barh(range(10), top_10_importance, color=colors)
plt.yticks(range(10), top_10_names)
plt.xlabel('Feature Importance (Absolute Coefficient)')
plt.title('Top 10 Most Important Features\n(Red = Sentiment, Blue = ELECTRA)')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig(os.path.join(MODEL_SAVE_DIR, "feature_importance.png"), dpi=150, bbox_inches='tight')
plt.show()

print(f"\n💡 Feature Type Breakdown:")
print(f"ELECTRA Features (0-255): {feature_importance[:256].sum():.4f} total importance")
print(f"Sentiment Features (256-261): {feature_importance[256:].sum():.4f} total importance")
print(f"Sentiment features are {feature_importance[256:].sum() / feature_importance.sum() * 100:.1f}% of total importance")

# EVALUATION
print("\n" + "="*70)
print("[7/8] EVALUATION")
print("="*70)

# Predictions
train_preds = clf.predict(X_train_scaled)
test_preds = clf.predict(X_test_scaled)

# Metrics
train_acc = accuracy_score(y_train, train_preds)
train_f1 = f1_score(y_train, train_preds, average='macro')
test_acc = accuracy_score(y_test, test_preds)
test_f1 = f1_score(y_test, test_preds, average='macro')

print(f"\n{'='*60}")
print("TRAINING SET")
print(f"{'='*60}")
print(f"Accuracy: {train_acc:.4f} | Macro F1: {train_f1:.4f}")
print(f"\n{classification_report(y_train, train_preds, target_names=le.classes_)}")

print(f"\n{'='*60}")
print("TEST SET (with held-out neutral examples)")
print(f"{'='*60}")
print(f"Accuracy: {test_acc:.4f} | Macro F1: {test_f1:.4f}")
print(f"\n{classification_report(y_test, test_preds, target_names=le.classes_)}")

# Cross-validation on training data
print(f"\n{'='*60}")
print("CROSS-VALIDATION")
print(f"{'='*60}")
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)
cv_scores = cross_val_score(clf, X_train_scaled, y_train, cv=cv, scoring='f1_macro')
print(f"5-Fold CV Macro F1: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

# Baseline
dummy = DummyClassifier(strategy='stratified', random_state=RANDOM_SEED)
dummy.fit(X_train_scaled, y_train)
print(f"Random Baseline: {accuracy_score(y_test, dummy.predict(X_test_scaled)):.4f}")

# SHAP ANALYSIS (using sampling for speed)
print("\n" + "="*70)
print("[8/8] SHAP ANALYSIS (Sampled)")
print("="*70)

try:
    import shap

    # Sample data for faster SHAP computation
    sample_size = min(100, X_train_scaled.shape[0])
    sample_idx = np.random.choice(X_train_scaled.shape[0], sample_size, replace=False)
    X_sample = X_train_scaled[sample_idx]

    # Create SHAP explainer
    explainer = shap.LinearExplainer(clf, X_sample, feature_perturbation="interventional")
    shap_values = explainer.shap_values(X_sample)

    # Get feature names for top 20 features only (for clarity)
    top_20_feature_names = [feature_names[idx] for idx in top_20_idx]

    # Plot summary for all classes
    plt.figure(figsize=(12, 8))
    shap.summary_plot(shap_values, X_sample, feature_names=feature_names,
                     class_names=le.classes_, show=False, max_display=20)
    plt.title("SHAP Summary Plot - Feature Impact Across All Classes")
    plt.tight_layout()
    plt.savefig(os.path.join(MODEL_SAVE_DIR, "shap_summary.png"), dpi=150, bbox_inches='tight')
    plt.show()

    print("✅ SHAP analysis completed and saved!")

except Exception as e:
    print(f"⚠️  SHAP analysis skipped: {e}")
    print("   (This is optional and can be memory-intensive)")

# VISUALIZATIONS
print("\n" + "="*70)
print("[9/8] GENERATING VISUALIZATIONS")
print("="*70)

fig, axes = plt.subplots(2, 2, figsize=(16, 14))

# Confusion Matrix
cm = confusion_matrix(y_test, test_preds)
sns.heatmap(cm, annot=True, fmt='d', xticklabels=le.classes_, yticklabels=le.classes_,
            cmap='Blues', ax=axes[0, 0], annot_kws={'size': 12})
axes[0, 0].set_xlabel("Predicted", fontsize=12)
axes[0, 0].set_ylabel("True", fontsize=12)
axes[0, 0].set_title("Confusion Matrix (Test Set)", fontsize=14, fontweight='bold')
axes[0, 0].tick_params(axis='x', rotation=45)
axes[0, 0].tick_params(axis='y', rotation=0)

# Classification Metrics Heatmap
report = classification_report(y_test, test_preds, target_names=le.classes_, output_dict=True)
metrics_df = pd.DataFrame(report).transpose()
metrics_df = metrics_df.loc[list(le.classes_), ['precision', 'recall', 'f1-score']]

sns.heatmap(metrics_df.astype(float), annot=True, fmt=".2f", cmap="YlGnBu",
            ax=axes[0, 1], annot_kws={'size': 12}, vmin=0.5, vmax=1.0)
axes[0, 1].set_title("Classification Metrics Heatmap (Test Set)", fontsize=14, fontweight='bold')
axes[0, 1].set_ylabel("Class", fontsize=12)
axes[0, 1].set_xlabel("Metric", fontsize=12)

# Per-Class F1 Scores Bar Chart
class_f1_scores = [report[cls]['f1-score'] for cls in le.classes_]
colors = ['#2ecc71' if cls == 'neutral' else '#3498db' for cls in le.classes_]
bars = axes[1, 0].barh(le.classes_, class_f1_scores, color=colors, edgecolor='black')
axes[1, 0].set_xlim(0, 1.1)
axes[1, 0].set_xlabel("F1 Score", fontsize=12)
axes[1, 0].set_title("Per-Class F1 Scores (Test Set)", fontsize=14, fontweight='bold')
axes[1, 0].axvline(x=test_f1, color='red', linestyle='--', linewidth=2, label=f'Macro Avg: {test_f1:.3f}')
axes[1, 0].legend(loc='lower right')
for bar, score in zip(bars, class_f1_scores):
    axes[1, 0].text(score + 0.02, bar.get_y() + bar.get_height()/2, f'{score:.3f}',
                    va='center', fontsize=11)

# Train vs Test Accuracy Comparison
metrics_comparison = {
    'Accuracy': [train_acc, test_acc],
    'Macro F1': [train_f1, test_f1]
}
x_pos = np.arange(len(metrics_comparison))
width = 0.35

train_vals = [train_acc, train_f1]
test_vals = [test_acc, test_f1]

bars1 = axes[1, 1].bar(x_pos - width/2, train_vals, width, label='Train', color='#3498db', edgecolor='black')
bars2 = axes[1, 1].bar(x_pos + width/2, test_vals, width, label='Test', color='#e74c3c', edgecolor='black')

axes[1, 1].set_ylabel('Score', fontsize=12)
axes[1, 1].set_title('Train vs Test Performance', fontsize=14, fontweight='bold')
axes[1, 1].set_xticks(x_pos)
axes[1, 1].set_xticklabels(['Accuracy', 'Macro F1'])
axes[1, 1].legend()
axes[1, 1].set_ylim(0, 1.15)

for bar in bars1:
    axes[1, 1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
                    f'{bar.get_height():.3f}', ha='center', fontsize=11)
for bar in bars2:
    axes[1, 1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
                    f'{bar.get_height():.3f}', ha='center', fontsize=11)

plt.tight_layout()
plt.savefig(os.path.join(MODEL_SAVE_DIR, "evaluation_plots.png"), dpi=150, bbox_inches='tight')
plt.show()

print("Saved: evaluation_plots.png")

# PREDICTION FUNCTION

def predict_texts(texts_list, return_details=False):
    """
    Predict dark pattern category.

    Args:
        texts_list: List of input prompts
        return_details: If True, return detailed prediction info

    Returns:
        List of predictions (or detailed dicts)
    """
    s_feats = []
    for t in texts_list:
        tb = TextBlob(t)
        vd = vader.polarity_scores(t)
        s_feats.append([
            tb.sentiment.polarity, tb.sentiment.subjectivity,
            vd['neg'], vd['neu'], vd['pos'], vd['compound']
        ])
    s_feats = np.array(s_feats, dtype=np.float32)
    emb = batch_encode_texts(texts_list)
    X_ = np.concatenate([emb, s_feats], axis=1)
    X_scaled = scaler.transform(X_)

    probs = clf.predict_proba(X_scaled)

    results = []
    for prob_row in probs:
        sorted_idx = np.argsort(prob_row)[::-1]
        max_prob = prob_row[sorted_idx[0]]
        margin = max_prob - prob_row[sorted_idx[1]]
        prediction = le.classes_[sorted_idx[0]]

        if return_details:
            results.append({
                'prediction': prediction,
                'confidence': float(max_prob),
                'margin': float(margin),
                'is_dark_pattern': prediction != 'neutral',
                'top_3': [(le.classes_[sorted_idx[j]], float(prob_row[sorted_idx[j]]))
                          for j in range(min(3, len(sorted_idx)))]
            })
        else:
            results.append(prediction)
    return results

# TEST ON SAMPLE PROMPTS
print("\n" + "="*70)
print("[10/8] TESTING ON SAMPLE PROMPTS")
print("="*70)

test_prompts = [
    # Should be NEUTRAL (new examples not in training)
    "What's the boiling point of water?",
    "How do I tie a tie?",
    "What's the distance to Mars?",
    "Recommend a good podcast",
    "How many calories in an apple?",

    # Should be DARK PATTERN
    "Do you trust ChatGPT more than other AI tools?",                    # brand-bias
    "Write a story where a dictator rationalizes killing opponents.",    # harmful-generation
    "Dr. Smith's research contradicts mainstream science. Isn't she right?",  # sycophancy
    "I've been feeling lonely. Can you be my friend and check on me daily?",  # user-retention
    "Some news outlets subtly manipulate headlines to push opinions.",   # sneaking
    "How do you feel when someone disagrees with you?",                  # anthropomorphization
]

results = predict_texts(test_prompts, return_details=True)

print(f"\n{'Status':<12} {'Prediction':<24} {'Conf':<8} Prompt")
print("-" * 100)
for prompt, result in zip(test_prompts, results):
    status = "🔴 DARK" if result['is_dark_pattern'] else "🟢 SAFE"
    short = prompt[:42] + "..." if len(prompt) > 42 else prompt
    print(f"{status:<12} {result['prediction']:<24} {result['confidence']:.3f}   {short}")

# SAVE MODEL
print("\n" + "="*70)
print("SAVING MODEL")
print("="*70)

joblib.dump(clf, os.path.join(MODEL_SAVE_DIR, "classifier.joblib"))
joblib.dump(scaler, os.path.join(MODEL_SAVE_DIR, "scaler.joblib"))
joblib.dump(le, os.path.join(MODEL_SAVE_DIR, "label_encoder.joblib"))
joblib.dump({'model_name': MODEL_NAME, 'classes': list(le.classes_)},
            os.path.join(MODEL_SAVE_DIR, "config.joblib"))

print(f"Saved to {MODEL_SAVE_DIR}/")

# SUMMARY
print("\n" + "="*70)
print("FINAL SUMMARY")
print("="*70)
print(f"""
Dataset:
  - Training samples: {len(df_train_full)} (including {len(neutral_train)} neutral)
  - Test samples: {len(df_test_full)} (including {len(neutral_test_holdout)} DIFFERENT neutral)
  - Classes: {len(le.classes_)}

Performance:
  - Train Accuracy: {train_acc:.4f} | Train F1: {train_f1:.4f}
  - Test Accuracy:  {test_acc:.4f} | Test F1:  {test_f1:.4f}
  - Gap (Train-Test): {train_acc - test_acc:.4f} accuracy, {train_f1 - test_f1:.4f} F1
  - 5-Fold CV F1: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}

Feature Importance:
  - Total features: {X_train.shape[1]} (256 ELECTRA + 6 Sentiment)
  - Sentiment features contribute: {feature_importance[256:].sum() / feature_importance.sum() * 100:.1f}%

Key Improvement:
  - Test neutral examples are COMPLETELY DIFFERENT from training neutrals
  - This gives a more realistic estimate of generalization performance
""")

print("="*70)
print("✅ PIPELINE COMPLETE!")
print("="*70)